name: Build & Package Flax Editor
on: [push, pull_request]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-editor:
    name: Build Flax Editor (Windows)
    runs-on: windows-2022
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Vulkan
        uses: ./.github/actions/vulkan

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Print .NET info
        run: |
          dotnet --info
          dotnet workload --info

      - name: Build Editor
        run: |
          .\Development\Scripts\Windows\CallBuildTool.bat -build -log -printSDKs -dotnet=8 -arch=x64 -platform=Windows -configuration=Development -buildtargets=FlaxEditor

      - name: Archive full Editor build
        run: |
          powershell Compress-Archive -Path ".\Build\Windows\x64\FlaxEditor\*" -DestinationPath ".\FlaxEditor-Full.zip" -Force

      - name: Upload Editor artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlaxEditor-Full
          path: .\FlaxEditor-Full.zip
