name: Build Flax Editor (Windows)

on: [push, pull_request]

env:
DOTNET_NOLOGO: true
DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
build-editor:
name: Build Flax Editor (Windows x64)
runs-on: windows-2022

```
steps:
- name: Checkout repository
  uses: actions/checkout@v4
  with:
    lfs: true

- name: Setup Vulkan
  uses: ./.github/actions/vulkan

- name: Setup .NET
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.0.x

- name: Print .NET info
  run: |
    dotnet --info
    dotnet workload --info

- name: Build Flax Editor
  run: |
    .\Development\Scripts\Windows\CallBuildTool.bat -build -log -printSDKs -dotnet=8 -arch=x64 -platform=Windows -configuration=Development -buildtargets=FlaxEditor

- name: Upload Editor Build
  uses: actions/upload-artifact@v4
  with:
    name: flax-editor-windows
    path: |
      Binaries/
      Cache/
      Content/
      Engine/
```
