name: Build Windows Game

on: [push, pull_request]

env:
DOTNET_NOLOGO: true
DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
build-windows:
name: Build & Package (Windows x64)
runs-on: windows-2022

```
steps:
- name: Checkout repository
  uses: actions/checkout@v4
  with:
    lfs: true

- name: Setup Vulkan
  uses: ./.github/actions/vulkan

- name: Setup .NET
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.0.x

- name: Print .NET info
  run: |
    dotnet --info
    dotnet workload --info

- name: Build game
  run: |
    .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Release -buildtargets=FlaxGame

- name: Package game
  run: |
    .\Development\Scripts\Windows\CallBuildTool.bat -package -arch=x64 -platform=Windows -configuration=Release

- name: Upload packaged build
  uses: actions/upload-artifact@v4
  with:
    name: windows-game-build
    path: Package/
```
